kind: pipeline
type: kubernetes
name: default

workspace:
  path: /drone/src

steps:
  - name: build-cache
    image: node:lts-alpine
    commands:
      - "yarn install -W"
  # - name: lint
  #   image: node:lts-alpine
  #   commands:
  #     - "yarn lint:website"
  #     - "yarn lint:server"
  - name: build-plugin
    image: node:lts-alpine
    commands:
      - "yarn workspace plugin build"
  - name: build-website
    image: node:lts-alpine
    commands:
      - "APP_NAME=Hackathon BASE_URL=http://hackathon.rlab.app NODE_ENV=production yarn workspace website build"
  - name: build-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: falabrowse/review-n-rating
      tags:
        - latest
        - ${DRONE_COMMIT:0:8}
  # - name: deploy
  #   image: alpine/helm:3.2.1
  #   environment:
  #     KUBECONFIG_FILE:
  #       from_secret: KUBECONFIG
  #     MONGODB_PASSWORD:
  #       from_secret: MONGODB_PASSWORD
  #     MONGODB_USERNAME:
  #       from_secret: MONGODB_USERNAME
  #     MONGODB_HOST:
  #       from_secret: MONGODB_HOST
  #     GITHUB_LOGIN_CLIENT_ID:
  #       from_secret: GITHUB_LOGIN_CLIENT_ID
  #     GITHUB_LOGIN_CLIENT_SECRET:
  #       from_secret: GITHUB_LOGIN_CLIENT_SECRET
  #     REDIS_HOST:
  #       from_secret: REDIS_HOST
  #     KUBEMQ_HOST:
  #       from_secret: KUBEMQ_HOST
  #   commands:
  #     - echo "$KUBECONFIG_FILE" > kubeconfig.b64
  #     - export KUBECONFIG="$PWD/kubeconfig.yml"
  #     - base64 -d kubeconfig.b64 > kubeconfig.yml
  #     - helm repo add mychart https://reezpatel.github.io/helm_charts
  #     - echo "$KUBECONFIG_FILE"
  #     - helm repo update
  #     - helm search repo dev
  #     - helm upgrade --wait --install --atomic devpunk mychart/devpunk -n devpunk -f helm.values.yml --set-string image.tag="${DRONE_COMMIT:0:8}" --set-string env.MONGODB_PASSWORD="$MONGODB_PASSWORD" --set-string env.MONGODB_USERNAME="$MONGODB_USERNAME" --set-string env.MONGODB_HOST="$MONGODB_HOST" --set-string env.GITHUB_LOGIN_CLIENT_ID="$GITHUB_LOGIN_CLIENT_ID" --set-string env.GITHUB_LOGIN_CLIENT_SECRET="$GITHUB_LOGIN_CLIENT_SECRET" --set-string env.REDIS_HOST="$REDIS_HOST" --set-string env.KUBEMQ_HOST="$KUBEMQ_HOST"
    # when:
    #   event:
    #     - promote
    #   target:
    #     - production
